-- product 상품 추가

-- 건식사료
insert into product
(product_name,product_imgurl,product_price,product_stock,product_detail,product_size,product_color,maker,product_mfd,product_poo,product_epd,pc_no)
 values('성견용 진돗개 사료 도그썬 진돗개용 10kg', '/projectdengdeng/imagefile/product_img/food/food0001.png', 30200, 100, 'details', 'size', 'color', 'JS글로벌', null,
 '대한민국', null, 6),
 ('D17 애견사료 넥스탑 주노 5kg 소형견용', '/projectdengdeng/imagefile/product_img/food/food0002.png', 19900, 100, 'details', 'size', 'color', 'NEXTOP', null,
 '대한민국', null, 6),
 ('D17 애견 사료 우성 넥스탑 애플 15kg', '/projectdengdeng/imagefile/product_img/food/food0003.png', 49600, 100, 'details', 'size', 'color', 'NEXTOP', null,
 '대한민국', null, 6),
 ('팜스코 필드 스타 10kg(진도) 성견용 건식 강아지사료', '/projectdengdeng/imagefile/product_img/food/food0004.png', 24400, 100, 'details', 'size', 'color', '주식회사 팜스코', null,
 '대한민국', null, 6),
 ('닥스훈트 어덜트 1.5kg 강아지 주식 1P 건사료 개밥', '/projectdengdeng/imagefile/product_img/food/food0005.png', 34500, 100, 'details', 'size', 'color', 'Royal Canin', null,
 '프랑스', null, 6),
 ('D17 프로베스트 루키 5kg 반려견 사료', '/projectdengdeng/imagefile/product_img/food/food0006.png', 20800, 100, 'details', 'size', 'color', 'Probest', null,
 '대한민국', null, 6),
 ('ANF 6FREE GOLD 식스프리 골드 독 오리 연어 1.8kg', '/projectdengdeng/imagefile/product_img/food/food0007.png', 25000, 100, 'details', 'size', 'color', 'ANF', null,
 '대한민국', null, 6),
 ('독 사료 패밀리 중대형견 10kg', '/projectdengdeng/imagefile/product_img/food/food0008.png', 28100, 100, 'details', 'size', 'color', 'DogRang', null,
 '대한민국', null, 6),
 ('강아지 노령견용 그레인프리 연어 5kg 무곡물 사료', '/projectdengdeng/imagefile/product_img/food/food0009.png', 48600, 100, 'details', 'size', 'color', 'Mombless', null,
 '대한민국', null, 6),
 ('강아지 전견용 그레인프리 양고기 5kg 무곡물 사료', '/projectdengdeng/imagefile/product_img/food/food0010.png', 48600, 100, 'details', 'size', 'color', 'Mombless', null,
 '대한민국', null, 6),
 ('강아지 전견용 그레인프리 오리 5kg 무곡물 사료', '/projectdengdeng/imagefile/product_img/food/food0011.png', 48600, 100, 'details', 'size', 'color', 'Mombless', null,
 '대한민국', null, 6),
 ('강아지 양고기 닭고기 5kg 1P 애견 전견용 건식 사료', '/projectdengdeng/imagefile/product_img/food/food0012.png', 27300, 100, 'details', 'size', 'color', 'AnyPet', null,
 '대한민국', null, 6),
 ('강아지 연어 감자 5kg 1P 애견 전견용 건식 사료', '/projectdengdeng/imagefile/product_img/food/food0013.png', 27300, 100, 'details', 'size', 'color', 'AnyPet', null,
 '대한민국', null, 6),
 ('강아지 오리 호박 5kg 1P 애견 전견용 건식 사료', '/projectdengdeng/imagefile/product_img/food/food0014.png', 27300, 100, 'details', 'size', 'color', 'AnyPet', null,
 '대한민국', null, 6),
 ('강아지 건식 사료 뉴스카이 성견 15kg', '/projectdengdeng/imagefile/product_img/food/food0015.png', 24800, 100, 'details', 'size', 'color', '제일사료 주식회사', null,
 '대한민국', null, 6),
 ('강아지 오가닉 양고기 2kg 반려견 성견용 건식 사료', '/projectdengdeng/imagefile/product_img/food/food0016.png', 25000, 100, 'details', 'size', 'color', '주식회사 팜스코', null,
 '대한민국', null, 6),
 ('강아지 오가닉 연어 2kg 반려견 성견용 건식 사료', '/projectdengdeng/imagefile/product_img/food/food0017.png', 25000, 100, 'details', 'size', 'color', '주식회사 팜스코', null,
 '대한민국', null, 6),
 ('강아지 오가닉 오리 2kg 반려견 성견용 건식 사료', '/projectdengdeng/imagefile/product_img/food/food0018.png', 25000, 100, 'details', 'size', 'color', '주식회사 팜스코', null,
 '대한민국', null, 6),
 ('강아지 초록잎홍합 닭고기 2kg 반려견 유기농 사료', '/projectdengdeng/imagefile/product_img/food/food0019.png', 26700, 100, 'details', 'size', 'color', '주식회사 팜스코', null,
 '대한민국', null, 6),
 ('강아지 유기농쌀 소고기 2kg 반려견 성견용 건식 사료', '/projectdengdeng/imagefile/product_img/food/food0020.png', 26700, 100, 'details', 'size', 'color', '주식회사 팜스코', null,
 '대한민국', null, 6),
 ('강아지 유기농 현비 슈퍼푸드 2kg 반려견 건식 사료', '/projectdengdeng/imagefile/product_img/food/food0021.png', 26700, 100, 'details', 'size', 'color', '주식회사 팜스코', null,
 '대한민국', null, 6);
 
 
 -- 습식사료
insert into product
(product_name,product_imgurl,product_price,product_stock,product_detail,product_size,product_color,maker,product_mfd,product_poo,product_epd,pc_no)
 values('강아지 사료 닭고기 수제 습식사료 화식 대용량500g', '/projectdengdeng/imagefile/product_img/food/food0022.png', 20000, 100, 'details', 'size', 'color', '로우키친', null,
 '대한민국', null, 7),
 ('강아지 사료 소고기 수제 습식사료 화식 대용량500g', '/projectdengdeng/imagefile/product_img/food/food0023.png', 27300, 100, 'details', 'size', 'color', '로우키친', null,
 '대한민국', null, 7),
 ('로얄캐닌 코트 케어 85g 12P 강아지 파우치 애견 사료', '/projectdengdeng/imagefile/product_img/food/food0024.png', 25700, 100, 'details', 'size', 'color', 'Royal Canin', null,
 '프랑스', null, 7),
 ('로얄캐닌 퍼피 미니 85g 12P 강아지 파우치 애견 사료', '/projectdengdeng/imagefile/product_img/food/food0025.png', 22300, 100, 'details', 'size', 'color', 'Royal Canin', null,
 '프랑스', null, 7),
 ('기능성 반건조 강아지사료 1kg 황태활력 200gx5개입', '/projectdengdeng/imagefile/product_img/food/food0026.png', 24700, 100, 'details', 'size', 'color', '더텐 소프트', null,
 '대한민국', null, 7),
 ('기능성 반건조 1kg 인섹트알러지 200gx5개입', '/projectdengdeng/imagefile/product_img/food/food0027.png', 24700, 100, 'details', 'size', 'color', '더텐 소프트', null,
 '대한민국', null, 7),
 ('기능성 반건조 강아지사료 1kg 연어피부 200gx5개입', '/projectdengdeng/imagefile/product_img/food/food0028.png', 24700, 100, 'details', 'size', 'color', '더텐 소프트', null,
 '대한민국', null, 7),
 ('기능성 반건조 강아지사료 1kg 소고기관절 200gx5개입', '/projectdengdeng/imagefile/product_img/food/food0029.png', 24700, 100, 'details', 'size', 'color', '더텐 소프트', null,
 '대한민국', null, 7),
 ('네츄럴오 유기농 쌀과 연어퍼피 2kg', '/projectdengdeng/imagefile/product_img/food/food0030.png', 33300, 100, 'details', 'size', 'color', '주식회사 팜스코', null,
 '대한민국', null, 7),
 ('네츄럴오 유기농 쌀과 소고기 2kg', '/projectdengdeng/imagefile/product_img/food/food0031.png', 32500, 100, 'details', 'size', 'color', '주식회사 팜스코', null,
 '대한민국', null, 7),
 ('네츄럴오 유기농 쌀과 슈퍼푸드 2kg', '/projectdengdeng/imagefile/product_img/food/food0032.png', 32500, 100, 'details', 'size', 'color', '주식회사 팜스코', null,
 '대한민국', null, 7),
 ('네츄럴오 유기농 쌀과 초록잎홍합 2kg', '/projectdengdeng/imagefile/product_img/food/food0033.png', 32500, 100, 'details', 'size', 'color', '주식회사 팜스코', null,
 '대한민국', null, 7),
 ('네츄럴오 유기농 쌀과 연어 2kg', '/projectdengdeng/imagefile/product_img/food/food0034.png', 30800, 100, 'details', 'size', 'color', '주식회사 팜스코', null,
 '대한민국', null, 7),
 ('네츄럴오 유기농 쌀과 오리 2kg', '/projectdengdeng/imagefile/product_img/food/food0035.png', 30800, 100, 'details', 'size', 'color', '주식회사 팜스코', null,
 '대한민국', null, 7),
 ('네츄럴오 유기농 쌀과 양고기 2kg', '/projectdengdeng/imagefile/product_img/food/food0036.png', 30800, 100, 'details', 'size', 'color', '주식회사 팜스코', null,
 '대한민국', null, 7),
 ('건강백서 2kg 말티즈 전용 사료', '/projectdengdeng/imagefile/product_img/food/food0037.png', 26000, 100, 'details', 'size', 'color', 'Nutrena', null,
 '대한민국', null, 7),
 ('건강백서 2kg 푸들 전용 사료', '/projectdengdeng/imagefile/product_img/food/food0038.png', 26000, 100, 'details', 'size', 'color', 'Nutrena', null,
 '대한민국', null, 7),
 ('건강백서 2kg 포메라니안 전용 사료', '/projectdengdeng/imagefile/product_img/food/food0039.png', 26000, 100, 'details', 'size', 'color', 'Nutrena', null,
 '대한민국', null, 7),
 ('건강백서 2kg 요크셔테리어 전용 사료', '/projectdengdeng/imagefile/product_img/food/food0040.png', 26000, 100, 'details', 'size', 'color', 'Nutrena', null,
 '대한민국', null, 7),
 ('건강백서 2kg 시츄 전용 사료', '/projectdengdeng/imagefile/product_img/food/food0041.png', 26000, 100, 'details', 'size', 'color', 'Nutrena', null,
 '대한민국', null, 7);

-- 강아지껌
insert into product
(product_name,product_imgurl,product_price,product_stock,product_detail,product_size,product_color,maker,product_mfd,product_poo,product_epd,pc_no)
 values
('내품애 실속형(1kg/오리말이껌 4.5인치)', '/projectdengdeng/imagefile/product_img/snack/snanck0001.png', 28500, 100, 'details', 'size', 'color', '내품애', null,
 '중국', null, 8),
('내품애 실속형(1kg/치킨말이껌 2.5인치)', '/projectdengdeng/imagefile/product_img/snack/snanck0002.png', 27600, 100, 'details', 'size', 'color', '내품애', null,
 '중국', null, 8),
('내품애 실속형(1kg/우유껌 치킨말이스틱)', '/projectdengdeng/imagefile/product_img/snack/snanck0003.png', 20300, 100, 'details', 'size', 'color', '내품애', null,
 '중국', null, 8),
('내품애 실속형(1kg/치킨말이껌 4.5인치)', '/projectdengdeng/imagefile/product_img/snack/snanck0004.png', 27600, 100, 'details', 'size', 'color', '내품애', null,
 '중국', null, 8),
('내품애 실속형(1kg/우유껌 오리말이스틱)', '/projectdengdeng/imagefile/product_img/snack/snanck0005.png', 22400, 100, 'details', 'size', 'color', '내품애', null,
 '중국', null, 8),
('내품애 실속형(1kg/오리말이껌 2.5인치)', '/projectdengdeng/imagefile/product_img/snack/snanck0006.png', 28500, 100, 'details', 'size', 'color', '내품애', null,
 '중국', null, 8),
('뽀부장의 간식생활 치킨연어포 300gX50개', '/projectdengdeng/imagefile/product_img/food/snanck0007.png', 126000, 100, 'details', 'size', 'color', '헤세드요셉', null, 
'중국', null, 8),
('뽀부장의 간식생활 치킨우유껌 300gX50개', '/projectdengdeng/imagefile/product_img/food/snanck0008.png', 126000, 100, 'details', 'size', 'color', '헤세드요셉', null, 
'중국', null, 8),
('뽀부장의 간식생활 치킨윙사시미 300gX50개', '/projectdengdeng/imagefile/product_img/food/snanck0009.png', 126000, 100, 'details', 'size', 'color', '헤세드요셉', null, 
'중국', null, 8),
('뽀부장의 간식생활 치킨비스켓 300gX50개', '/projectdengdeng/imagefile/product_img/food/snanck0010.png', 126000, 100, 'details', 'size', 'color', '헤세드요셉', null, 
'중국', null, 8),
('뽀부장의 간식생활 치킨혼합 300gX50개', '/projectdengdeng/imagefile/product_img/food/snanck0011.png', 126000, 100, 'details', 'size', 'color', '헤세드요셉', null, 
'중국', null, 8),
('뽀부장의 간식생활 오리고구마 300gX50개', '/projectdengdeng/imagefile/product_img/food/snanck0012.png', 126000, 100, 'details', 'size', 'color', '헤세드요셉', null, 
'중국', null, 8),
('뽀부장의 간식생활 오리쌀스틱 300gX50개', '/projectdengdeng/imagefile/product_img/food/snanck0013.png', 126000, 100, 'details', 'size', 'color', '헤세드요셉', null, 
'중국', null, 8),
('뽀부장의 간식생활 오리우유껌 300gX50개', '/projectdengdeng/imagefile/product_img/food/snanck0014.png', 126000, 100, 'details', 'size', 'color', '헤세드요셉', null, 
'중국', null, 8),
('뽀부장의 간식생활 건식꽈배기 300gX50개', '/projectdengdeng/imagefile/product_img/food/snanck0015.png', 126000, 100, 'details', 'size', 'color', '헤세드요셉', null, 
'중국', null, 8),
('뽀부장의 간식생활 닭갈비 300gX50개', '/projectdengdeng/imagefile/product_img/food/snanck0016.png', 126000, 100, 'details', 'size', 'color', '헤세드요셉', null, 
'중국', null, 8),
('뽀부장의 간식생활 미니닭갈비 300gX50개', '/projectdengdeng/imagefile/product_img/food/snanck0017.png', 126000, 100, 'details', 'size', 'color', '헤세드요셉', null, 
'중국', null, 8),
('뽀부장의 간식생활 젤리꽈배기 300gX50개', '/projectdengdeng/imagefile/product_img/food/snanck0018.png', 126000, 100, 'details', 'size', 'color', '헤세드요셉', null, 
'중국', null, 8),
('뽀부장의 간식생활 치킨고구마 300gX50개', '/projectdengdeng/imagefile/product_img/food/snanck0019.png', 126000, 100, 'details', 'size', 'color', '헤세드요셉', null, 
'중국', null, 8),
('뽀부장의 간식생활 치킨덤벨 300gX50개', '/projectdengdeng/imagefile/product_img/food/snanck0020.png', 126000, 100, 'details', 'size', 'color', '헤세드요셉', null, 
'중국', null, 8);

-- 수제간식

 
select * from product;